services:
  - type: web
    name: subsidized-energy-backend
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: subsidized-energy-db
          property: connectionString
      - key: JWT_SECRET
        sync: false
      - key: CREDENTIALS_SECRET
        sync: false
      - key: DEPLOYER_PRIVATE_KEY
        sync: false
      - key: SOLANA_PRIVATE_KEY
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: BASE_SEPOLIA_RPC_URL
        value: https://sepolia.base.org
      - key: SUB_TOKEN_ADDRESS
        value: 0x34a42157C86489E102bC7F611c0d05696FA45682
      - key: SRE_TOKEN_ADDRESS
        value: 0xB60fbCc17a0aeb405bC55a816ed39B2ff6480ABF
      - key: ENERGY_REGISTRY_ADDRESS
        value: 0x21AE62E009f04259173C0f08ED5650dE53bD9CE7
      - key: SOLANA_RPC_URL
        value: https://api.devnet.solana.com
      - key: SOLANA_ENERGY_REGISTRY
        value: E93p3yX6mxswv1yBn6gcZvsPCqckyupUVQKuk6YLNyYR
      - key: ACTIVE_CHAINS
        value: base,solana
      - key: ALLOW_MOCK_INVERTERS
        value: "false"

databases:
  - name: subsidized-energy-db
    databaseName: subsidized_energy
    plan: free
